# Generated by Django 4.2.9 on 2026-05-13 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('versions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('approval_type', models.CharField(choices=[('sequential', 'Sequential'), ('parallel', 'Parallel')], max_length=50)),
                ('max_stages', models.IntegerField(default=10)),
                ('escalation_hours', models.IntegerField(default=48)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'workflow_templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('in_review', 'In Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('escalated', 'Escalated')], default='draft', max_length=50)),
                ('current_stage', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='versions.document')),
                ('initiated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflows.workflowtemplate')),
            ],
            options={
                'db_table': 'workflow_instances',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage_number', models.IntegerField()),
                ('decision', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('escalated', 'Escalated')], max_length=50)),
                ('comments', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('approver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workflow_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='workflows.workflowinstance')),
            ],
            options={
                'db_table': 'workflow_approvals',
                'ordering': ['-decided_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowStage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage_number', models.IntegerField()),
                ('stage_name', models.CharField(max_length=255)),
                ('approver_role', models.CharField(blank=True, max_length=50)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('required', models.BooleanField(default=True)),
                ('approver_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='workflows.workflowtemplate')),
            ],
            options={
                'db_table': 'workflow_stages',
                'ordering': ['stage_number'],
                'unique_together': {('template', 'stage_number')},
            },
        ),
        migrations.AddIndex(
            model_name='workflowinstance',
            index=models.Index(fields=['document'], name='workflow_in_documen_8a323d_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowinstance',
            index=models.Index(fields=['status'], name='workflow_in_status_a4291a_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowinstance',
            index=models.Index(fields=['created_at'], name='workflow_in_created_bd522a_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowapproval',
            index=models.Index(fields=['workflow_instance'], name='workflow_ap_workflo_488dfa_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowapproval',
            index=models.Index(fields=['decided_at'], name='workflow_ap_decided_a7a372_idx'),
        ),
    ]
