# Generated by Django 4.2.9 on 2026-05-08 20:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('input_file', models.FileField(upload_to='conversions/input/%Y/%m/%d/')),
                ('output_file', models.FileField(blank=True, null=True, upload_to='conversions/output/%Y/%m/%d/')),
                ('conversion_type', models.CharField(choices=[('word_to_pdf', 'Word to PDF'), ('image_to_pdf', 'Image to PDF'), ('pdf_to_word', 'PDF to Word'), ('pdf_to_image', 'PDF to Image'), ('excel_to_pdf', 'Excel to PDF'), ('ppt_to_pdf', 'PowerPoint to PDF'), ('pdf_to_text', 'PDF to Text')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('input_size', models.BigIntegerField(default=0)),
                ('output_size', models.BigIntegerField(default=0)),
                ('processing_time', models.FloatField(default=0.0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversion_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversion Job',
                'verbose_name_plural': 'Conversion Jobs',
                'db_table': 'conversion_jobs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='conversion__user_id_79a028_idx'), models.Index(fields=['status'], name='conversion__status_c48025_idx'), models.Index(fields=['conversion_type'], name='conversion__convers_3535eb_idx')],
            },
        ),
    ]
