# Generated by Django 4.2.9 on 2026-05-13 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemMetrics',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('total_uploads_24h', models.IntegerField(default=0)),
                ('total_uploads_7d', models.IntegerField(default=0)),
                ('total_uploads_30d', models.IntegerField(default=0)),
                ('upload_success_rate', models.FloatField(default=0.0)),
                ('jobs_pending', models.IntegerField(default=0)),
                ('jobs_processing', models.IntegerField(default=0)),
                ('jobs_completed', models.IntegerField(default=0)),
                ('jobs_failed', models.IntegerField(default=0)),
                ('queue_depth', models.IntegerField(default=0)),
                ('avg_wait_time_seconds', models.FloatField(default=0.0)),
                ('active_users', models.IntegerField(default=0)),
                ('total_users', models.IntegerField(default=0)),
                ('total_storage_bytes', models.BigIntegerField(default=0)),
                ('storage_by_department', models.JSONField(blank=True, default=dict)),
                ('api_response_time_p50', models.FloatField(default=0.0)),
                ('api_response_time_p95', models.FloatField(default=0.0)),
                ('api_response_time_p99', models.FloatField(default=0.0)),
                ('queue_processing_rate', models.FloatField(default=0.0)),
                ('error_rate', models.FloatField(default=0.0)),
                ('cache_hit_rate', models.FloatField(default=0.0)),
                ('cpu_usage_percent', models.FloatField(default=0.0)),
                ('memory_usage_percent', models.FloatField(default=0.0)),
                ('disk_usage_percent', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'system_metrics',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='system_metr_timesta_f576a5_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('activity_type', models.CharField(max_length=100)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_activities',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='user_activi_user_id_6bb195_idx'), models.Index(fields=['activity_type', '-timestamp'], name='user_activi_activit_b512c7_idx')],
            },
        ),
    ]
