# Generated by Django 4.2.9 on 2026-05-13 10:14

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=500)),
                ('file_size', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('chunk_size', models.IntegerField(default=10485760)),
                ('total_chunks', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('uploaded_chunks', models.IntegerField(default=0)),
                ('checksum_sha256', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='in_progress', max_length=20)),
                ('storage_temp_path', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'upload_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UploadChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chunk_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('chunk_size', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('checksum_sha256', models.CharField(max_length=64)),
                ('storage_path', models.TextField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('upload_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='uploads.uploadsession')),
            ],
            options={
                'db_table': 'upload_chunks',
                'ordering': ['chunk_number'],
            },
        ),
        migrations.AddIndex(
            model_name='uploadsession',
            index=models.Index(fields=['user', 'status'], name='upload_sess_user_id_73c91f_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadsession',
            index=models.Index(fields=['created_at'], name='upload_sess_created_3de5bb_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadsession',
            index=models.Index(fields=['status'], name='upload_sess_status_f1db9b_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadchunk',
            index=models.Index(fields=['upload_session', 'chunk_number'], name='upload_chun_upload__05a40c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='uploadchunk',
            unique_together={('upload_session', 'chunk_number')},
        ),
    ]
