# Generated by Django 4.2.9 on 2026-05-08 20:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompressionJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_file', models.FileField(upload_to='uploads/original/%Y/%m/%d/')),
                ('compressed_file', models.FileField(blank=True, null=True, upload_to='uploads/compressed/%Y/%m/%d/')),
                ('compression_level', models.CharField(choices=[('low', 'Low Compression'), ('medium', 'Medium Compression'), ('high', 'High Compression')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('original_size', models.BigIntegerField(default=0, help_text='Original file size in bytes')),
                ('compressed_size', models.BigIntegerField(default=0, help_text='Compressed file size in bytes')),
                ('compression_ratio', models.FloatField(default=0.0, help_text='Compression ratio percentage')),
                ('processing_time', models.FloatField(default=0.0, help_text='Processing time in seconds')),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compression_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Compression Job',
                'verbose_name_plural': 'Compression Jobs',
                'db_table': 'compression_jobs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='compression_user_id_aeb42c_idx'), models.Index(fields=['status'], name='compression_status_69593f_idx')],
            },
        ),
    ]
