# Generated by Django 4.2.9 on 2026-05-13 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=500)),
                ('original_filename', models.CharField(max_length=500)),
                ('file_type', models.CharField(max_length=50)),
                ('current_version', models.IntegerField(default=1)),
                ('file_size', models.BigIntegerField()),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('checksum_sha256', models.CharField(max_length=64)),
                ('storage_path', models.TextField()),
                ('storage_bucket', models.CharField(blank=True, max_length=255)),
                ('encrypted', models.BooleanField(default=True)),
                ('encryption_key_id', models.CharField(blank=True, max_length=255)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.IntegerField()),
                ('file_size', models.BigIntegerField()),
                ('checksum_sha256', models.CharField(max_length=64)),
                ('storage_path', models.TextField()),
                ('is_rollback', models.BooleanField(default=False)),
                ('rollback_from_version', models.IntegerField(blank=True, null=True)),
                ('change_description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='versions.document')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'document_versions',
                'ordering': ['-version_number'],
                'indexes': [models.Index(fields=['document', 'version_number'], name='document_ve_documen_ff5d1a_idx'), models.Index(fields=['created_at'], name='document_ve_created_c8d81d_idx')],
                'unique_together': {('document', 'version_number')},
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['owner', 'is_deleted'], name='documents_owner_i_1d623b_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['file_type'], name='documents_file_ty_4b3ae1_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['created_at'], name='documents_created_3c6eaa_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['checksum_sha256'], name='documents_checksu_fa9a5a_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['department'], name='documents_departm_f00baa_idx'),
        ),
    ]
