# Generated by Django 4.2.9 on 2026-05-14 18:11

from django.conf import settings
import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query_text', models.TextField()),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('result_count', models.IntegerField(default=0)),
                ('execution_time_ms', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'search_queries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='search_quer_user_id_486cee_idx'), models.Index(fields=['-created_at'], name='search_quer_created_824a49_idx')],
            },
        ),
        migrations.CreateModel(
            name='DocumentIndex',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_id', models.UUIDField(db_index=True)),
                ('filename', models.CharField(max_length=500)),
                ('file_type', models.CharField(db_index=True, max_length=50)),
                ('file_size', models.BigIntegerField()),
                ('content', models.TextField(blank=True)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(null=True)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('department', models.CharField(blank=True, db_index=True, max_length=100)),
                ('workflow_status', models.CharField(blank=True, db_index=True, max_length=50)),
                ('created_at', models.DateTimeField(db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relevance_score', models.FloatField(default=0.0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indexed_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'document_search_index',
                'ordering': ['-created_at'],
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='document_se_search__314dd6_gin'), models.Index(fields=['owner', 'file_type'], name='document_se_owner_i_c652e5_idx'), models.Index(fields=['created_at'], name='document_se_created_04c195_idx'), models.Index(fields=['workflow_status'], name='document_se_workflo_2d03b1_idx'), models.Index(fields=['department'], name='document_se_departm_7788de_idx')],
            },
        ),
    ]
